# ASSIGNMENT-12

### 1) Create numpy array and perform following operation

#### Convert 1D array to 2D > Print Array Attributes(Like shape, dimenssion, data type, itemsize)

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr.reshape(2, 3)  
print(arr_2d)


[[1 2 3]
 [4 5 6]]


In [2]:
print("Shape:", arr_2d.shape)
print("Dimension:", arr_2d.ndim)
print("Data type:", arr_2d.dtype)
print("Item size:", arr_2d.itemsize)


Shape: (2, 3)
Dimension: 2
Data type: int64
Item size: 8


### Create a 3×3 NumPy array of all 9

In [3]:
arr_3x3 = np.full((3, 3), 9)
print(arr_3x3)


[[9 9 9]
 [9 9 9]
 [9 9 9]]


###  Create a 1D array of 10 evenly spaced values between 25 and 125 

In [4]:
arr_lin = np.linspace(25, 125, 10)
print(arr_lin)


[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


### Convert a Python list into a NumPy array

In [5]:
py_list = [10, 20, 30, 40]
np_arr = np.array(py_list)
print(np_arr)


[10 20 30 40]


###  Reverse a 1D NumPy array 


In [6]:
rev_arr = np_arr[::-1]
print(rev_arr)


[40 30 20 10]


####  Create a 4×4×3 array and extract value at its second set, first row and last column > 

In [7]:
arr_3d = np.arange(48).reshape(4, 4, 3)
print(arr_3d[1, 0, -1])   


14


#### Create a 4×4 and Extract Odd Rows and Even Columns

In [8]:
arr_4x4 = np.arange(16).reshape(4, 4)
print(arr_4x4[::2, 1::2])


[[ 1  3]
 [ 9 11]]


##### Slice the first two rows and first two columns of econd set from a 4×4×3 array 

In [9]:
print(arr_3d[1, :2, :2])


[[12 13]
 [15 16]]


 #### Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]

In [10]:
arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i, j] % 2 != 0:
            arr[i, j] = -1
print(arr)


[[-1 56 78 -1]
 [-1 82 -1 24]]


#### Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4]

In [11]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr)
print(indices)


(array([0, 2, 4, 6]),)


####  Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)


Addition: [5 7 9]
Multiplication: [ 4 10 18]


 ### Multiply two NumPy arrays element by element. > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

In [13]:
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)
print("Dot Product:", dot_product)


Dot Product: 1875
