## ASSIGNMENT  11

### 1) Combining a one and a two-dimensional NumPy Array 2)

In [2]:
import numpy as np

arr=np.array([1,2,3])
arr1=np.array([[6,7,8],
              [9,8,7]])
res1=arr+arr1
print(res1)

[[ 7  9 11]
 [10 10 10]]


### Flatten a 2d numpy array into 1d array 3)

In [3]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print("Flattened array:", flat)
arr = np.array([1, 2, 3, 4, 5])
#Reverse a numpy array
rev = arr[::-1]
print("Reversed array:", rev)


Flattened array: [1 2 3 4]
Reversed array: [5 4 3 2 1]


### 4) Practice operations 

## Get the maximum value from given array
## Get the minimum value from given array

In [4]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])


# Max & Min
print("Max:", arr.max())
print("Min:", arr.min())

Max: 60
Min: 10


## Find the number of rows and columns of a given array using NumPy 

In [5]:


print("Shape:", arr.shape)

Shape: (2, 3)


###  Select the elements from a given array (each element and specific element) 


In [6]:
print("All elements:", arr)
print("Specific element [0,1]:", arr[0,1])

All elements: [[10 20 30]
 [40 50 60]]
Specific element [0,1]: 20


### Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy 


In [7]:
total = 0
for row in arr:
    for val in row:
        total += val
print("Sum using loop:", total)
# Arithmetic operations
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Sum using loop: 210
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


###  5) Iterate 3D array using for loop and nditer 

In [8]:
arr3d = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])

# Using for loop
for block in arr3d:
    for row in block:
        for val in row:
            print(val, end=" ")
print()

# Using nditer
for val in np.nditer(arr3d):
    print(val, end=" ")


1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 

### 6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) ->

### Calculate average mean median mode values of two NumPy 2d-arrays

In [9]:
import numpy as np


# Example 2D arrays
arr1 = np.array([[3, 4], [5, 6]])
arr2 = np.array([[1, 0], [7, 8]])

# Average of arrays
avg = (arr1 + arr2) / 2
print("Average:\n", avg)

# Mean
print("Mean:", np.mean([arr1, arr2]))

# Median
print("Median:", np.median([arr1, arr2]))

# Mode
combined = np.concatenate([arr1.flatten(), arr2.flatten()])
print(combined)




Average:
 [[2. 2.]
 [6. 7.]]
Mean: 4.25
Median: 4.5
[3 4 5 6 1 0 7 8]


In [10]:
import numpy as np
from collections import Counter
arr1 = np.array([[3, 4], [5, 6]])
arr2 = np.array([[1, 0], [7, 8]])
combined = np.concatenate([arr1.flatten(), arr2.flatten()])
counter = Counter(combined)
mode_value = counter.most_common(1)[0][0]

print("Mode using Counter:", mode_value)

Mode using Counter: 3
